#!/bin/sh

RSUPPORT_USER=${RSUPPORT_USER:-support}
RSUPPORT_UID=${RSUPPORT_UID:-1337}
RSUPPORT_PASS=${RSUPPORT_PASS:-5uPP0rt}
RSUPPORT_SSHPORT=${RSUPPORT_SSHPORT:-2222}
RSUPPORT_ENABLE_PASSWORDAUTH=${RSUPPORT_ENABLE_PASSWORDAUTH:-true}

mkdir -p /home/$RSUPPORT_USER/.ssh
adduser -s /sbin/nologin -D $RSUPPORT_USER --home /home/$RSUPPORT_USER -u $RSUPPORT_UID
chown -R $RSUPPORT_USER:$RSUPPORT_USER /home/$RSUPPORT_USER
echo $RSUPPORT_USER:$RSUPPORT_PASS | chpasswd

/bin/sh -c "/usr/sbin/dropbear -FEwga -G ${RSUPPORT_USER} -p ${RSUPPORT_SSHPORT}"